spring:
  application:
    name: zebroid
    url: https://github.com/laster04
zonky:
  host: 'https://api.zonky.cz/'
  path-loans: 'loans/marketplace'
  batch-size: 500
  init-max-batch-size: 1000
  user-agent: ${spring.application.name}/@version@ (${spring.application.url}})
  loans-scheduler: '0 */5 * * * *'
  loans-scheduler-fixrate: 5 * 60 * 1000
feign:
  client:
    config:
      loans:
        connectTimeout: 5000
